server:
  port: 8081
spring:
  application:
    name: task-management-system
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/task_management_system_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
jwt:
  secret:
    access: 0JrRg9C00LAg0LjQtNC10Lwg0LzRiyDRgSDQv9GP0YLQvtGH0LrQvtC80JrRg9C00LAg0LjQtNC10Lwg0LzRiyDRgSDQv9GP0YLQvtGH0LrQvtC8
    access-expiration: 10 # Время жизни в минутах
    refresh: RW5jb2RlIHRvIEJhc2U2NCBmb3JtYXQ=RW5jb2RlIHRvIEJhc2U2NCBmb3JtYXQ=RW5jb2RlIHRvIEJhc2U2NCBmb3JtYXQ=
    refresh-expiration: 30 # Время жизни в минутах